/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
//PARTIE SOFIENE	
  GtkWidget *fenetre_ajouter_animal;
  GtkWidget *gestion_des___quipement_agricoles;
  GtkWidget *liste_equipement;
  GtkWidget *fenetre_afficher_animal;
  GtkWidget *fenetre_ajouter_equipement;
  GtkWidget *fenetre_entretient_equipement;
  GtkWidget *fenetre_ajouter_date_entretient;
  GtkWidget *fenetre_login_principale;
  GtkWidget *fenetre_menu;
//PARTIE OUMAYMA+HIBA
  GtkWidget *liste_capteurs;
  GtkWidget *ajouter_capteur;
  GtkWidget *fenetre_ajouter_enH;
  GtkWidget *fenetre_afficher_enH;
  GtkWidget *fenetre_ajouter_enT;
  GtkWidget *fenetre_afficher_enT;
  GtkWidget *modifier_capteur;
  GtkWidget *f_chercher_capteur;
  GtkWidget *capteur;
  GtkWidget *capteur_defect;
  GtkWidget *gestion_capteur;
  GtkWidget *gestion_client;
  GtkWidget *fenetre_ajouter_client;
  GtkWidget *fenetre_traitement_des_reclamations;
  GtkWidget *fenetre_liste_des_reclamations;
  GtkWidget *fenetre_afficher_client;
  GtkWidget *fenetre_modifier_client;
  GtkWidget *fenetre_responsable;
  GtkWidget *liste_commande;
  GtkWidget *ajoute_commande;
//PARTIE DALY
  GtkWidget *treeview;
  GtkWidget *treeview_abs;
  GtkWidget *fenetre_fiche_information_ajout;
  GtkWidget *fenetre_modifier_informations;
  GtkWidget *fenetre_ajouter_absence;
  GtkWidget *fenetre_responsable_ouvrier;
//PARTIE TOUIHRI
  GtkWidget *fenetre_gestion_des_employees;
  GtkWidget *fenetre_liste_des_employees;
  GtkWidget *fenetre_ajouter_employe;
  GtkWidget *fenetre_modifier_employe;
//PARTIE AZIZ
GtkWidget *Espace_responsable_de__production;
GtkWidget *Calendrier_de_plantations;
GtkWidget *fenetre_ajouter_plante;
GtkWidget *fenetre_afficher_calendrier;
GtkWidget *fenetre_choix;
GtkWidget *fenetre_modifier_plante;
GtkWidget *Lannee_la_plus_seche;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
//la fenetre d'ouverture de l'application		
  fenetre_login_principale = create_fenetre_login_principale();
  gtk_widget_show (fenetre_login_principale);

  gtk_main ();
  return 0;
}

