/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajouter_reclamation (void);
GtkWidget* create_fenetre_afficher_reclamation (void);
GtkWidget* create_fenetre_ajouter_client (void);
GtkWidget* create_fenetre_afficher_client (void);
GtkWidget* create_fenetre_modifier_client (void);
GtkWidget* create_gestion_client (void);
