/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Espace_responsable_de_production (void);
GtkWidget* create_Calandrier_de_plantations (void);
GtkWidget* create_L_ann__e_la_plus_s__che (void);
