/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Espace_responsable_de_production (void)
{
  GtkWidget *Espace_responsable_de_production;
  GtkWidget *fixed1;
  GtkWidget *button2;
  GtkWidget *button1;
  GtkWidget *_;
  GtkWidget *Retour;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label79;

  Espace_responsable_de_production = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_responsable_de_production), _("Espace responsable de production"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Espace_responsable_de_production), fixed1);

  button2 = gtk_button_new_with_mnemonic (_("Gestion des troupeaux"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 32, 176);
  gtk_widget_set_size_request (button2, 344, 40);

  button1 = gtk_button_new_with_mnemonic (_("Gestion du calandrier de plantation vegetals"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 32, 104);
  gtk_widget_set_size_request (button1, 344, 40);

  _ = gtk_label_new (_("Responsable de production"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed1), _, 16, 16);
  gtk_widget_set_size_request (_, 368, 32);

  Retour = gtk_button_new ();
  gtk_widget_show (Retour);
  gtk_fixed_put (GTK_FIXED (fixed1), Retour, 24, 256);
  gtk_widget_set_size_request (Retour, 80, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Retour), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox5), label79, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_responsable_de_production, Espace_responsable_de_production, "Espace_responsable_de_production");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, button2, "button2");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, button1, "button1");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, _, "_");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, Retour, "Retour");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, image5, "image5");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de_production, label79, "label79");

  return Espace_responsable_de_production;
}

GtkWidget*
create_Calandrier_de_plantations (void)
{
  GtkWidget *Calandrier_de_plantations;
  GtkWidget *fixed2;
  GtkWidget *table1;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *Supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label77;
  GtkWidget *Retour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label76;
  GtkWidget *Ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label78;

  Calandrier_de_plantations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Calandrier_de_plantations), _("Calandrier de plantations"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Calandrier_de_plantations), fixed2);

  table1 = gtk_table_new (7, 13, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed2), table1, 216, 128);
  gtk_widget_set_size_request (table1, 208, 112);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table1), label34, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new (_("Janvier"));
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table1), label35, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label36 = gtk_label_new (_("Fevrier"));
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table1), label36, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  label37 = gtk_label_new (_("Mars"));
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table1), label37, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label38 = gtk_label_new (_("Avril"));
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table1), label38, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label39 = gtk_label_new (_("Mai"));
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table1), label39, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  label40 = gtk_label_new (_("Juin"));
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table1), label40, 6, 7, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label41 = gtk_label_new (_("Juillet"));
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table1), label41, 7, 8, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("Aout"));
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table1), label42, 8, 9, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("Septembre"));
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table1), label43, 9, 10, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label44 = gtk_label_new (_("Octobre"));
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table1), label44, 10, 11, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label45 = gtk_label_new (_("Novembre"));
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table1), label45, 11, 12, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  label46 = gtk_label_new (_("Decembre"));
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table1), label46, 12, 13, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  label47 = gtk_label_new (_("Carottes"));
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table1), label47, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  label48 = gtk_label_new (_("Piments"));
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table1), label48, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  label49 = gtk_label_new (_("Tomates"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table1), label49, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  label50 = gtk_label_new (_("Radis"));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table1), label50, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  label51 = gtk_label_new (_("Pommes de terre"));
  gtk_widget_show (label51);
  gtk_table_attach (GTK_TABLE (table1), label51, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label51), 0, 0.5);

  label52 = gtk_label_new (_("Oignons"));
  gtk_widget_show (label52);
  gtk_table_attach (GTK_TABLE (table1), label52, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label52), 0, 0.5);

  label53 = gtk_label_new (_("    x"));
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table1), label53, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  label54 = gtk_label_new (_("    X"));
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table1), label54, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  label55 = gtk_label_new (_("  X"));
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table1), label55, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label55), 0, 0.5);

  label56 = gtk_label_new (_("   X"));
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table1), label56, 6, 7, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label56), 0, 0.5);

  label58 = gtk_label_new (_("  X"));
  gtk_widget_show (label58);
  gtk_table_attach (GTK_TABLE (table1), label58, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label58), 0, 0.5);

  label59 = gtk_label_new (_("   X"));
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table1), label59, 6, 7, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);

  label60 = gtk_label_new (_("    X"));
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table1), label60, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label60), 0, 0.5);

  label61 = gtk_label_new (_("    X"));
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table1), label61, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label61), 0, 0.5);

  label62 = gtk_label_new (_("   X"));
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table1), label62, 5, 6, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);

  label63 = gtk_label_new (_("    X"));
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table1), label63, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  label64 = gtk_label_new (_("    X"));
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table1), label64, 4, 5, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label64), 0, 0.5);

  label65 = gtk_label_new (_("    X"));
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table1), label65, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label65), 0, 0.5);

  label66 = gtk_label_new (_("    X"));
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table1), label66, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label66), 0, 0.5);

  label67 = gtk_label_new (_("  X"));
  gtk_widget_show (label67);
  gtk_table_attach (GTK_TABLE (table1), label67, 5, 6, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label67), 0, 0.5);

  label68 = gtk_label_new (_("   X"));
  gtk_widget_show (label68);
  gtk_table_attach (GTK_TABLE (table1), label68, 6, 7, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label68), 0, 0.5);

  label69 = gtk_label_new (_("     X"));
  gtk_widget_show (label69);
  gtk_table_attach (GTK_TABLE (table1), label69, 7, 8, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label69), 0, 0.5);

  label70 = gtk_label_new (_("    X"));
  gtk_widget_show (label70);
  gtk_table_attach (GTK_TABLE (table1), label70, 8, 9, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label70), 0, 0.5);

  label71 = gtk_label_new (_("           X"));
  gtk_widget_show (label71);
  gtk_table_attach (GTK_TABLE (table1), label71, 9, 10, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label71), 0, 0.5);

  label72 = gtk_label_new (_("  X"));
  gtk_widget_show (label72);
  gtk_table_attach (GTK_TABLE (table1), label72, 5, 6, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label72), 0, 0.5);

  label73 = gtk_label_new (_("   X"));
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table1), label73, 6, 7, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);

  Supprimer = gtk_button_new ();
  gtk_widget_show (Supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), Supprimer, 560, 288);
  gtk_widget_set_size_request (Supprimer, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox3), label77, FALSE, FALSE, 0);

  Retour = gtk_button_new ();
  gtk_widget_show (Retour);
  gtk_fixed_put (GTK_FIXED (fixed2), Retour, 784, 288);
  gtk_widget_set_size_request (Retour, 104, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (Retour), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox2), label76, FALSE, FALSE, 0);

  Ajouter = gtk_button_new ();
  gtk_widget_show (Ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), Ajouter, 328, 288);
  gtk_widget_set_size_request (Ajouter, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox4), label78, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Calandrier_de_plantations, Calandrier_de_plantations, "Calandrier_de_plantations");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, table1, "table1");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label34, "label34");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label35, "label35");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label36, "label36");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label37, "label37");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label38, "label38");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label39, "label39");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label40, "label40");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label41, "label41");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label42, "label42");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label43, "label43");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label44, "label44");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label45, "label45");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label46, "label46");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label47, "label47");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label48, "label48");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label49, "label49");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label50, "label50");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label51, "label51");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label52, "label52");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label53, "label53");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label54, "label54");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label55, "label55");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label56, "label56");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label58, "label58");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label59, "label59");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label60, "label60");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label61, "label61");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label62, "label62");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label63, "label63");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label64, "label64");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label65, "label65");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label66, "label66");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label67, "label67");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label68, "label68");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label69, "label69");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label70, "label70");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label71, "label71");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label72, "label72");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label73, "label73");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, image3, "image3");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label77, "label77");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, Retour, "Retour");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, image2, "image2");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label76, "label76");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, image4, "image4");
  GLADE_HOOKUP_OBJECT (Calandrier_de_plantations, label78, "label78");

  return Calandrier_de_plantations;
}

GtkWidget*
create_L_ann__e_la_plus_s__che (void)
{
  GtkWidget *L_ann__e_la_plus_s__che;
  GtkWidget *fixed3;
  GtkWidget *curve1;
  GtkWidget *Retour;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label75;
  GtkWidget *Bilan_de_l_ann__e_la_plus_s__che;

  L_ann__e_la_plus_s__che = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (L_ann__e_la_plus_s__che), _("L'ann\303\251e la plus s\303\251che"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (L_ann__e_la_plus_s__che), fixed3);

  curve1 = gtk_curve_new ();
  gtk_widget_show (curve1);
  gtk_fixed_put (GTK_FIXED (fixed3), curve1, 55, 45);
  gtk_widget_set_size_request (curve1, 16, 16);
  gtk_curve_set_range (GTK_CURVE (curve1), 0, 400, 100, 400);

  Retour = gtk_button_new ();
  gtk_widget_show (Retour);
  gtk_fixed_put (GTK_FIXED (fixed3), Retour, 2, 307);
  gtk_widget_set_size_request (Retour, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Retour), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox1), label75, FALSE, FALSE, 0);

  Bilan_de_l_ann__e_la_plus_s__che = gtk_label_new (_("Bilan de l'ann\303\251e la plus s\303\251che\n                     (Courbe)"));
  gtk_widget_show (Bilan_de_l_ann__e_la_plus_s__che);
  gtk_fixed_put (GTK_FIXED (fixed3), Bilan_de_l_ann__e_la_plus_s__che, 32, 8);
  gtk_widget_set_size_request (Bilan_de_l_ann__e_la_plus_s__che, 376, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (L_ann__e_la_plus_s__che, L_ann__e_la_plus_s__che, "L_ann__e_la_plus_s__che");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, curve1, "curve1");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, Retour, "Retour");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, image1, "image1");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, label75, "label75");
  GLADE_HOOKUP_OBJECT (L_ann__e_la_plus_s__che, Bilan_de_l_ann__e_la_plus_s__che, "Bilan_de_l_ann__e_la_plus_s__che");

  return L_ann__e_la_plus_s__che;
}

