/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Smart_Farm;
  GtkWidget *Se_connecter;
  GtkWidget *creer_votre_compte;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Smart_Farm = create_Smart_Farm ();
  gtk_widget_show (Smart_Farm);
  Se_connecter = create_Se_connecter ();
  gtk_widget_show (Se_connecter);
  creer_votre_compte = create_creer_votre_compte ();
  gtk_widget_show (creer_votre_compte);

  gtk_main ();
  return 0;
}

