/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_liste_des_reclamations (void);
GtkWidget* create_fenetre_traitement_des_reclamations (void);
GtkWidget* create_fenetre_ajouter_reclamation (void);
GtkWidget* create_fenetre_entrer (void);
