/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_treeview (void);
GtkWidget* create_fenetre_fiche_information_ajout (void);
GtkWidget* create_fenetre_ajouter_absence (void);
GtkWidget* create_fenetre_responsable_ouvrier (void);
GtkWidget* create_treeview_abs (void);
GtkWidget* create_fenetre_modifier_informations (void);
