/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Smart_Farm (void);
GtkWidget* create_Se_connecter (void);
GtkWidget* create_creer_votre_compte (void);
GtkWidget* create_Votre_commande (void);
