/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Smart_Farm (void)
{
  GtkWidget *Smart_Farm;
  GtkWidget *fixed2;
  GtkWidget *menubar1;
  GtkWidget *se_connecter1;
  GtkWidget *se_connecter1_menu;
  GtkWidget *se_connecter3;
  GtkWidget *creer_un_compte2;
  GtkWidget *votre_compte2;
  GtkWidget *vos_commandes2;
  GtkWidget *reclamations2;
  GtkWidget *s__parateur1;
  GtkWidget *aide1;
  GtkWidget *aide1_menu;
  GtkWidget *annuler_ma_commande_1;
  GtkWidget *suivre_ma_commande1;
  GtkWidget *chat_1;
  GtkWidget *table3;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *Fruits;
  GtkWidget *Legumes;
  GtkWidget *Veau;
  GtkWidget *Bovin;
  GtkWidget *Volaille_et_oeufs;
  GtkWidget *Miel;
  GtkWidget *Ble;
  GtkWidget *Avoines;
  GtkWidget *Cereales;
  GtkWidget *Panier;
  GtkWidget *label8;

  Smart_Farm = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Smart_Farm), _("Smart Farm"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Smart_Farm), fixed2);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_fixed_put (GTK_FIXED (fixed2), menubar1, 144, 8);
  gtk_widget_set_size_request (menubar1, 224, 56);

  se_connecter1 = gtk_menu_item_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (se_connecter1);
  gtk_container_add (GTK_CONTAINER (menubar1), se_connecter1);

  se_connecter1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (se_connecter1), se_connecter1_menu);

  se_connecter3 = gtk_menu_item_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (se_connecter3);
  gtk_container_add (GTK_CONTAINER (se_connecter1_menu), se_connecter3);

  creer_un_compte2 = gtk_menu_item_new_with_mnemonic (_("Creer un compte"));
  gtk_widget_show (creer_un_compte2);
  gtk_container_add (GTK_CONTAINER (se_connecter1_menu), creer_un_compte2);

  votre_compte2 = gtk_menu_item_new_with_mnemonic (_("Votre compte"));
  gtk_widget_show (votre_compte2);
  gtk_container_add (GTK_CONTAINER (se_connecter1_menu), votre_compte2);

  vos_commandes2 = gtk_menu_item_new_with_mnemonic (_("Vos commandes"));
  gtk_widget_show (vos_commandes2);
  gtk_container_add (GTK_CONTAINER (se_connecter1_menu), vos_commandes2);

  reclamations2 = gtk_menu_item_new_with_mnemonic (_("Reclamations"));
  gtk_widget_show (reclamations2);
  gtk_container_add (GTK_CONTAINER (se_connecter1_menu), reclamations2);

  s__parateur1 = gtk_separator_menu_item_new ();
  gtk_widget_show (s__parateur1);
  gtk_container_add (GTK_CONTAINER (menubar1), s__parateur1);
  gtk_widget_set_sensitive (s__parateur1, FALSE);

  aide1 = gtk_menu_item_new_with_mnemonic (_("Aide"));
  gtk_widget_show (aide1);
  gtk_container_add (GTK_CONTAINER (menubar1), aide1);

  aide1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (aide1), aide1_menu);

  annuler_ma_commande_1 = gtk_menu_item_new_with_mnemonic (_("Annuler ma commande "));
  gtk_widget_show (annuler_ma_commande_1);
  gtk_container_add (GTK_CONTAINER (aide1_menu), annuler_ma_commande_1);

  suivre_ma_commande1 = gtk_menu_item_new_with_mnemonic (_("Suivre ma commande"));
  gtk_widget_show (suivre_ma_commande1);
  gtk_container_add (GTK_CONTAINER (aide1_menu), suivre_ma_commande1);

  chat_1 = gtk_menu_item_new_with_mnemonic (_("Chat "));
  gtk_widget_show (chat_1);
  gtk_container_add (GTK_CONTAINER (aide1_menu), chat_1);

  table3 = gtk_table_new (4, 4, FALSE);
  gtk_widget_show (table3);
  gtk_fixed_put (GTK_FIXED (fixed2), table3, 72, 280);
  gtk_widget_set_size_request (table3, 48, 48);

  label16 = gtk_label_new (_("Nos produits"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table3), label16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  label17 = gtk_label_new (_("Betail et volaille"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table3), label17, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Fruits et legumes"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table3), label18, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Cereales et ol\303\251agineux "));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  Fruits = gtk_button_new_with_mnemonic (_("Fruits"));
  gtk_widget_show (Fruits);
  gtk_table_attach (GTK_TABLE (table3), Fruits, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Legumes = gtk_button_new_with_mnemonic (_("Legumes"));
  gtk_widget_show (Legumes);
  gtk_table_attach (GTK_TABLE (table3), Legumes, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Veau = gtk_button_new_with_mnemonic (_("Veau"));
  gtk_widget_show (Veau);
  gtk_table_attach (GTK_TABLE (table3), Veau, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Bovin = gtk_button_new_with_mnemonic (_("Bovin"));
  gtk_widget_show (Bovin);
  gtk_table_attach (GTK_TABLE (table3), Bovin, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Volaille_et_oeufs = gtk_button_new_with_mnemonic (_("Volaille et oeufs"));
  gtk_widget_show (Volaille_et_oeufs);
  gtk_table_attach (GTK_TABLE (table3), Volaille_et_oeufs, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Miel = gtk_button_new_with_mnemonic (_("Miel"));
  gtk_widget_show (Miel);
  gtk_table_attach (GTK_TABLE (table3), Miel, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Ble = gtk_button_new_with_mnemonic (_("Bl\303\251"));
  gtk_widget_show (Ble);
  gtk_table_attach (GTK_TABLE (table3), Ble, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Avoines = gtk_button_new_with_mnemonic (_("Avoines"));
  gtk_widget_show (Avoines);
  gtk_table_attach (GTK_TABLE (table3), Avoines, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Cereales = gtk_button_new_with_mnemonic (_("C\303\251reales"));
  gtk_widget_show (Cereales);
  gtk_table_attach (GTK_TABLE (table3), Cereales, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Panier = gtk_button_new_with_mnemonic (_("Panier"));
  gtk_widget_show (Panier);
  gtk_fixed_put (GTK_FIXED (fixed2), Panier, 408, 32);
  gtk_widget_set_size_request (Panier, 66, 29);

  label8 = gtk_label_new (_("Smart Farm\nBordj Lella"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 0, 0);
  gtk_widget_set_size_request (label8, 136, 80);

  g_signal_connect ((gpointer) se_connecter1, "activate",
                    G_CALLBACK (on_se_connecter1_activate),
                    NULL);
  g_signal_connect ((gpointer) se_connecter3, "activate",
                    G_CALLBACK (on_se_connecter3_activate),
                    NULL);
  g_signal_connect ((gpointer) creer_un_compte2, "activate",
                    G_CALLBACK (on_creer_un_compte2_activate),
                    NULL);
  g_signal_connect ((gpointer) votre_compte2, "activate",
                    G_CALLBACK (on_votre_compte2_activate),
                    NULL);
  g_signal_connect ((gpointer) vos_commandes2, "activate",
                    G_CALLBACK (on_vos_commandes2_activate),
                    NULL);
  g_signal_connect ((gpointer) reclamations2, "activate",
                    G_CALLBACK (on_reclamations2_activate),
                    NULL);
  g_signal_connect ((gpointer) aide1, "activate",
                    G_CALLBACK (on_aide1_activate),
                    NULL);
  g_signal_connect ((gpointer) annuler_ma_commande_1, "activate",
                    G_CALLBACK (on_annuler_ma_commande_1_activate),
                    NULL);
  g_signal_connect ((gpointer) suivre_ma_commande1, "activate",
                    G_CALLBACK (on_suivre_ma_commande1_activate),
                    NULL);
  g_signal_connect ((gpointer) chat_1, "activate",
                    G_CALLBACK (on_chat_1_activate),
                    NULL);
  g_signal_connect ((gpointer) Panier, "clicked",
                    G_CALLBACK (on_Panier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Smart_Farm, Smart_Farm, "Smart_Farm");
  GLADE_HOOKUP_OBJECT (Smart_Farm, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Smart_Farm, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, se_connecter1, "se_connecter1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, se_connecter1_menu, "se_connecter1_menu");
  GLADE_HOOKUP_OBJECT (Smart_Farm, se_connecter3, "se_connecter3");
  GLADE_HOOKUP_OBJECT (Smart_Farm, creer_un_compte2, "creer_un_compte2");
  GLADE_HOOKUP_OBJECT (Smart_Farm, votre_compte2, "votre_compte2");
  GLADE_HOOKUP_OBJECT (Smart_Farm, vos_commandes2, "vos_commandes2");
  GLADE_HOOKUP_OBJECT (Smart_Farm, reclamations2, "reclamations2");
  GLADE_HOOKUP_OBJECT (Smart_Farm, s__parateur1, "s__parateur1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, aide1, "aide1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, aide1_menu, "aide1_menu");
  GLADE_HOOKUP_OBJECT (Smart_Farm, annuler_ma_commande_1, "annuler_ma_commande_1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, suivre_ma_commande1, "suivre_ma_commande1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, chat_1, "chat_1");
  GLADE_HOOKUP_OBJECT (Smart_Farm, table3, "table3");
  GLADE_HOOKUP_OBJECT (Smart_Farm, label16, "label16");
  GLADE_HOOKUP_OBJECT (Smart_Farm, label17, "label17");
  GLADE_HOOKUP_OBJECT (Smart_Farm, label18, "label18");
  GLADE_HOOKUP_OBJECT (Smart_Farm, label19, "label19");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Fruits, "Fruits");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Legumes, "Legumes");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Veau, "Veau");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Bovin, "Bovin");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Volaille_et_oeufs, "Volaille_et_oeufs");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Miel, "Miel");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Ble, "Ble");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Avoines, "Avoines");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Cereales, "Cereales");
  GLADE_HOOKUP_OBJECT (Smart_Farm, Panier, "Panier");
  GLADE_HOOKUP_OBJECT (Smart_Farm, label8, "label8");

  return Smart_Farm;
}

GtkWidget*
create_Se_connecter (void)
{
  GtkWidget *Se_connecter;
  GtkWidget *fixed3;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *E_mail;
  GtkWidget *mot_de_passe;
  GtkWidget *Rester_connecter;
  GtkWidget *creer_votre_compte;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label31;
  GtkWidget *SE_CONNECTER;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label32;

  Se_connecter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Se_connecter), _("Se connecter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Se_connecter), fixed3);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 112, 56);
  gtk_widget_set_size_request (entry2, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 112, 96);
  gtk_widget_set_size_request (entry3, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  E_mail = gtk_label_new (_("E-mail"));
  gtk_widget_show (E_mail);
  gtk_fixed_put (GTK_FIXED (fixed3), E_mail, 8, 64);
  gtk_widget_set_size_request (E_mail, 56, 24);

  mot_de_passe = gtk_label_new (_("mot de passe"));
  gtk_widget_show (mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed3), mot_de_passe, 0, 96);
  gtk_widget_set_size_request (mot_de_passe, 104, 24);

  Rester_connecter = gtk_check_button_new_with_mnemonic (_("Rester connecter"));
  gtk_widget_show (Rester_connecter);
  gtk_fixed_put (GTK_FIXED (fixed3), Rester_connecter, 104, 144);
  gtk_widget_set_size_request (Rester_connecter, 152, 24);

  creer_votre_compte = gtk_button_new ();
  gtk_widget_show (creer_votre_compte);
  gtk_fixed_put (GTK_FIXED (fixed3), creer_votre_compte, 184, 176);
  gtk_widget_set_size_request (creer_votre_compte, 168, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (creer_votre_compte), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("creer votre compte"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox3), label31, FALSE, FALSE, 0);

  SE_CONNECTER = gtk_button_new ();
  gtk_widget_show (SE_CONNECTER);
  gtk_fixed_put (GTK_FIXED (fixed3), SE_CONNECTER, 248, 144);
  gtk_widget_set_size_request (SE_CONNECTER, 136, 24);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (SE_CONNECTER), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("SE CONNECTER"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox4), label32, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Se_connecter, Se_connecter, "Se_connecter");
  GLADE_HOOKUP_OBJECT (Se_connecter, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Se_connecter, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Se_connecter, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Se_connecter, E_mail, "E_mail");
  GLADE_HOOKUP_OBJECT (Se_connecter, mot_de_passe, "mot_de_passe");
  GLADE_HOOKUP_OBJECT (Se_connecter, Rester_connecter, "Rester_connecter");
  GLADE_HOOKUP_OBJECT (Se_connecter, creer_votre_compte, "creer_votre_compte");
  GLADE_HOOKUP_OBJECT (Se_connecter, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Se_connecter, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Se_connecter, image3, "image3");
  GLADE_HOOKUP_OBJECT (Se_connecter, label31, "label31");
  GLADE_HOOKUP_OBJECT (Se_connecter, SE_CONNECTER, "SE_CONNECTER");
  GLADE_HOOKUP_OBJECT (Se_connecter, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Se_connecter, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Se_connecter, image4, "image4");
  GLADE_HOOKUP_OBJECT (Se_connecter, label32, "label32");

  return Se_connecter;
}

GtkWidget*
create_creer_votre_compte (void)
{
  GtkWidget *creer_votre_compte;
  GtkWidget *fixed4;
  GtkWidget *hseparator1;
  GtkWidget *entry4;
  GtkWidget *Nom;
  GtkWidget *entry5;
  GtkWidget *Prenom;
  GtkWidget *entry6;
  GtkWidget *Tel;
  GtkWidget *Adresse;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *E_mail;
  GtkWidget *mot_de_passe;
  GtkWidget *label3;
  GtkWidget *Se_connecter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label30;
  GtkWidget *button17;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label29;

  creer_votre_compte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (creer_votre_compte), _("creer votre compte"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (creer_votre_compte), fixed4);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator1, 152, 16);
  gtk_widget_set_size_request (hseparator1, 16, 16);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4, 48, 56);
  gtk_widget_set_size_request (entry4, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  Nom = gtk_label_new (_("Nom"));
  gtk_widget_show (Nom);
  gtk_fixed_put (GTK_FIXED (fixed4), Nom, 0, 56);
  gtk_widget_set_size_request (Nom, 41, 17);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 280, 56);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  Prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (Prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), Prenom, 216, 56);
  gtk_widget_set_size_request (Prenom, 64, 16);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 48, 96);
  gtk_widget_set_size_request (entry6, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  Tel = gtk_label_new (_("Tel"));
  gtk_widget_show (Tel);
  gtk_fixed_put (GTK_FIXED (fixed4), Tel, 0, 96);
  gtk_widget_set_size_request (Tel, 41, 17);

  Adresse = gtk_label_new (_("Adresse"));
  gtk_widget_show (Adresse);
  gtk_fixed_put (GTK_FIXED (fixed4), Adresse, 216, 96);
  gtk_widget_set_size_request (Adresse, 64, 16);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 280, 96);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 120, 136);
  gtk_widget_set_size_request (entry8, 288, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 120, 168);
  gtk_widget_set_size_request (entry9, 288, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  E_mail = gtk_label_new (_("E-mail"));
  gtk_widget_show (E_mail);
  gtk_fixed_put (GTK_FIXED (fixed4), E_mail, 56, 136);
  gtk_widget_set_size_request (E_mail, 41, 17);

  mot_de_passe = gtk_label_new (_("mot de passe"));
  gtk_widget_show (mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed4), mot_de_passe, 8, 168);
  gtk_widget_set_size_request (mot_de_passe, 112, 24);

  label3 = gtk_label_new (_("Creer votre compte"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed4), label3, 112, 8);
  gtk_widget_set_size_request (label3, 256, 32);

  Se_connecter = gtk_button_new ();
  gtk_widget_show (Se_connecter);
  gtk_fixed_put (GTK_FIXED (fixed4), Se_connecter, 216, 208);
  gtk_widget_set_size_request (Se_connecter, 136, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (Se_connecter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox2), label30, FALSE, FALSE, 0);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed4), button17, 120, 208);
  gtk_widget_set_size_request (button17, 90, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button17), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox1), label29, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (creer_votre_compte, creer_votre_compte, "creer_votre_compte");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, Prenom, "Prenom");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, Tel, "Tel");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, Adresse, "Adresse");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, E_mail, "E_mail");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, mot_de_passe, "mot_de_passe");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, label3, "label3");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, Se_connecter, "Se_connecter");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, image2, "image2");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, label30, "label30");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, button17, "button17");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, image1, "image1");
  GLADE_HOOKUP_OBJECT (creer_votre_compte, label29, "label29");

  return creer_votre_compte;
}

GtkWidget*
create_Votre_commande (void)
{
  GtkWidget *Votre_commande;
  GtkWidget *fixed5;
  GtkWidget *Passer_commande;
  GtkWidget *Annuler_commande;
  GtkWidget *table4;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *Vos_achats;

  Votre_commande = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Votre_commande), _("Votre commande"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Votre_commande), fixed5);

  Passer_commande = gtk_button_new_with_mnemonic (_("Passer commande"));
  gtk_widget_show (Passer_commande);
  gtk_fixed_put (GTK_FIXED (fixed5), Passer_commande, 56, 224);
  gtk_widget_set_size_request (Passer_commande, 144, 32);

  Annuler_commande = gtk_button_new_with_mnemonic (_("Annuler commande"));
  gtk_widget_show (Annuler_commande);
  gtk_fixed_put (GTK_FIXED (fixed5), Annuler_commande, 200, 224);
  gtk_widget_set_size_request (Annuler_commande, 144, 32);

  table4 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table4);
  gtk_fixed_put (GTK_FIXED (fixed5), table4, 152, 112);
  gtk_widget_set_size_request (table4, 138, 48);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 16);

  label20 = gtk_label_new (_("Articles"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table4), label20, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("Prix"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table4), label21, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new (_("quantite"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table4), label22, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label23 = gtk_label_new ("");
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table4), label23, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new ("");
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table4), label24, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new ("");
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table4), label25, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new ("");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table4), label26, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new ("");
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table4), label27, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new ("");
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table4), label28, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  Vos_achats = gtk_label_new (_("Vos achats"));
  gtk_widget_show (Vos_achats);
  gtk_fixed_put (GTK_FIXED (fixed5), Vos_achats, 8, 16);
  gtk_widget_set_size_request (Vos_achats, 128, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Votre_commande, Votre_commande, "Votre_commande");
  GLADE_HOOKUP_OBJECT (Votre_commande, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Votre_commande, Passer_commande, "Passer_commande");
  GLADE_HOOKUP_OBJECT (Votre_commande, Annuler_commande, "Annuler_commande");
  GLADE_HOOKUP_OBJECT (Votre_commande, table4, "table4");
  GLADE_HOOKUP_OBJECT (Votre_commande, label20, "label20");
  GLADE_HOOKUP_OBJECT (Votre_commande, label21, "label21");
  GLADE_HOOKUP_OBJECT (Votre_commande, label22, "label22");
  GLADE_HOOKUP_OBJECT (Votre_commande, label23, "label23");
  GLADE_HOOKUP_OBJECT (Votre_commande, label24, "label24");
  GLADE_HOOKUP_OBJECT (Votre_commande, label25, "label25");
  GLADE_HOOKUP_OBJECT (Votre_commande, label26, "label26");
  GLADE_HOOKUP_OBJECT (Votre_commande, label27, "label27");
  GLADE_HOOKUP_OBJECT (Votre_commande, label28, "label28");
  GLADE_HOOKUP_OBJECT (Votre_commande, Vos_achats, "Vos_achats");

  return Votre_commande;
}

