/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Liste_des_commandes_admin_RC_ (void);
GtkWidget* create_Passer_une_commande_client_ (void);
GtkWidget* create_Commande (void);
