/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_gestion_des_troupeaux (void);
GtkWidget* create_fenetre_ajouter_animal (void);
GtkWidget* create_gestion_des___quipement_agricoles (void);
GtkWidget* create_liste_equipement (void);
GtkWidget* create_fenetre_afficher_animal (void);
GtkWidget* create_fenetre_ajouter_equipement (void);
GtkWidget* create_fenetre_entretient_equipement (void);
GtkWidget* create_fenetre_ajouter_date_entretient (void);
GtkWidget* create_fenetre_menu (void);
GtkWidget* create_fenetre_modifier_animal (void);
GtkWidget* create_fenetre_modifier_equipement (void);
GtkWidget* create_fenetre_modifier_entretient (void);
