/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *fenetre_gestion_des_troupeaux;
  GtkWidget *fenetre_ajouter_animal;
  GtkWidget *gestion_des___quipement_agricoles;
  GtkWidget *liste_equipement;
  GtkWidget *fenetre_afficher_animal;
  GtkWidget *fenetre_ajouter_equipement;
  GtkWidget *fenetre_entretient_equipement;
  GtkWidget *fenetre_ajouter_date_entretient;
  GtkWidget *fenetre_menu;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  fenetre_menu = create_fenetre_menu ();
  gtk_widget_show (fenetre_menu);


  

  gtk_main ();
  return 0;
}

