/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Liste_des_commandes_admin_RC_ (void)
{
  GtkWidget *Liste_des_commandes_admin_RC_;
  GtkWidget *fixed1;
  GtkWidget *table1;
  GtkWidget *label2;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *label1;

  Liste_des_commandes_admin_RC_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Liste_des_commandes_admin_RC_), _("Liste des commandes"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Liste_des_commandes_admin_RC_), fixed1);

  table1 = gtk_table_new (3, 5, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed1), table1, 136, 144);
  gtk_widget_set_size_request (table1, 80, 48);

  label2 = gtk_label_new ("");
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table1), checkbutton1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table1), checkbutton2, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label3 = gtk_label_new (_(" Numero de la commande"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_(" Date"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_(" Lieux"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new (_(" Etat"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 24, 256);
  gtk_widget_set_size_request (button1, 120, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Liste des commandes :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 152, 32);
  gtk_widget_set_size_request (label1, 312, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Liste_des_commandes_admin_RC_, Liste_des_commandes_admin_RC_, "Liste_des_commandes_admin_RC_");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, table1, "table1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label2, "label2");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label3, "label3");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label4, "label4");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label5, "label5");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label6, "label6");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, button1, "button1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, image1, "image1");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label7, "label7");
  GLADE_HOOKUP_OBJECT (Liste_des_commandes_admin_RC_, label1, "label1");

  return Liste_des_commandes_admin_RC_;
}

GtkWidget*
create_Passer_une_commande_client_ (void)
{
  GtkWidget *Passer_une_commande_client_;
  GtkWidget *fixed2;
  GtkWidget *label8;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label13;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label10;
  GtkWidget *optionmenu1;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label14;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label15;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label16;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label17;

  Passer_une_commande_client_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Passer_une_commande_client_), _("Passer une commande"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Passer_une_commande_client_), fixed2);

  label8 = gtk_label_new (_("Passer une commande :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 80, 8);
  gtk_widget_set_size_request (label8, 256, 56);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 424, 88);
  gtk_widget_set_size_request (entry1, 96, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 248, 88);
  gtk_widget_set_size_request (entry2, 96, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label13 = gtk_label_new ("");
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 376, 80);
  gtk_widget_set_size_request (label13, 61, 22);

  label11 = gtk_label_new (_("Prix :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 416, 64);
  gtk_widget_set_size_request (label11, 61, 22);

  label12 = gtk_label_new (_("Produit :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 248, 64);
  gtk_widget_set_size_request (label12, 80, 24);

  label10 = gtk_label_new (_("Catalogue :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 48, 64);
  gtk_widget_set_size_request (label10, 104, 24);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_show (optionmenu1);
  gtk_fixed_put (GTK_FIXED (fixed2), optionmenu1, 56, 88);
  gtk_widget_set_size_request (optionmenu1, 104, 24);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 32, 168);
  gtk_widget_set_size_request (button2, 104, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox2), label14, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 168, 168);
  gtk_widget_set_size_request (button3, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox3), label15, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 304, 168);
  gtk_widget_set_size_request (button4, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox4), label16, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 440, 168);
  gtk_widget_set_size_request (button5, 120, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox5), label17, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Passer_une_commande_client_, Passer_une_commande_client_, "Passer_une_commande_client_");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label8, "label8");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label13, "label13");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label11, "label11");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label12, "label12");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label10, "label10");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, optionmenu1, "optionmenu1");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, button2, "button2");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, image2, "image2");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label14, "label14");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, button3, "button3");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, image3, "image3");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label15, "label15");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, button4, "button4");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, image4, "image4");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label16, "label16");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, button5, "button5");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, image5, "image5");
  GLADE_HOOKUP_OBJECT (Passer_une_commande_client_, label17, "label17");

  return Passer_une_commande_client_;
}

GtkWidget*
create_Commande (void)
{
  GtkWidget *Commande;
  GtkWidget *fixed3;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *label18;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label25;

  Commande = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Commande), _("votre commande"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Commande), fixed3);

  label19 = gtk_label_new (_("Reference :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 0, 88);
  gtk_widget_set_size_request (label19, 120, 24);

  label20 = gtk_label_new (_("Prix :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 0, 128);
  gtk_widget_set_size_request (label20, 64, 24);

  label21 = gtk_label_new (_("Entre le "));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 8, 168);
  gtk_widget_set_size_request (label21, 72, 24);

  label22 = gtk_label_new (_("Et le"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 248, 168);
  gtk_widget_set_size_request (label22, 61, 22);

  label23 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 8, 208);
  gtk_widget_set_size_request (label23, 112, 32);

  label24 = gtk_label_new (_("Etat :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 0, 248);
  gtk_widget_set_size_request (label24, 64, 32);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 120, 88);
  gtk_widget_set_size_request (entry3, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 120, 128);
  gtk_widget_set_size_request (entry4, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 120, 168);
  gtk_widget_set_size_request (entry5, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 312, 168);
  gtk_widget_set_size_request (entry6, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 120, 216);
  gtk_widget_set_size_request (entry7, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 120, 256);
  gtk_widget_set_size_request (entry8, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label18 = gtk_label_new (_("Votre commande :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 128, 16);
  gtk_widget_set_size_request (label18, 224, 40);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed3), button6, 16, 336);
  gtk_widget_set_size_request (button6, 96, 26);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox6), label25, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Commande, Commande, "Commande");
  GLADE_HOOKUP_OBJECT (Commande, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Commande, label19, "label19");
  GLADE_HOOKUP_OBJECT (Commande, label20, "label20");
  GLADE_HOOKUP_OBJECT (Commande, label21, "label21");
  GLADE_HOOKUP_OBJECT (Commande, label22, "label22");
  GLADE_HOOKUP_OBJECT (Commande, label23, "label23");
  GLADE_HOOKUP_OBJECT (Commande, label24, "label24");
  GLADE_HOOKUP_OBJECT (Commande, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Commande, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Commande, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Commande, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Commande, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Commande, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Commande, label18, "label18");
  GLADE_HOOKUP_OBJECT (Commande, button6, "button6");
  GLADE_HOOKUP_OBJECT (Commande, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Commande, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Commande, image6, "image6");
  GLADE_HOOKUP_OBJECT (Commande, label25, "label25");

  return Commande;
}

