/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Espace_responsable_de__production (void)
{
  GtkWidget *Espace_responsable_de__production;
  GtkWidget *fixed1;
  GtkWidget *image24;
  GtkWidget *_;
  GtkWidget *button1_choixcalendrier;
  GtkWidget *button2_gestiontroupeaux;
  GtkWidget *boutton_retour1;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label79;

  Espace_responsable_de__production = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_responsable_de__production), _("Espace_responsable_de_production"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Espace_responsable_de__production), fixed1);

  image24 = create_pixmap (Espace_responsable_de__production, "creative-cartoon-girl-financial-management-scene-png_218242.jpg");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed1), image24, 0, 0);
  gtk_widget_set_size_request (image24, 648, 472);

  _ = gtk_label_new (_("Responsable de production"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed1), _, 104, 0);
  gtk_widget_set_size_request (_, 368, 32);

  button1_choixcalendrier = gtk_button_new_with_mnemonic (_("Calendrier de plantations vegetals"));
  gtk_widget_show (button1_choixcalendrier);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_choixcalendrier, 120, 128);
  gtk_widget_set_size_request (button1_choixcalendrier, 344, 40);

  button2_gestiontroupeaux = gtk_button_new_with_mnemonic (_("La gestion des troupeaux"));
  gtk_widget_show (button2_gestiontroupeaux);
  gtk_fixed_put (GTK_FIXED (fixed1), button2_gestiontroupeaux, 120, 224);
  gtk_widget_set_size_request (button2_gestiontroupeaux, 344, 40);

  boutton_retour1 = gtk_button_new ();
  gtk_widget_show (boutton_retour1);
  gtk_fixed_put (GTK_FIXED (fixed1), boutton_retour1, 8, 376);
  gtk_widget_set_size_request (boutton_retour1, 80, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (boutton_retour1), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox5), label79, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1_choixcalendrier, "clicked",
                    G_CALLBACK (on_button1_verschoix_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_responsable_de__production, Espace_responsable_de__production, "Espace_responsable_de__production");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, image24, "image24");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, _, "_");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, button1_choixcalendrier, "button1_choixcalendrier");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, button2_gestiontroupeaux, "button2_gestiontroupeaux");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, boutton_retour1, "boutton_retour1");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, image5, "image5");
  GLADE_HOOKUP_OBJECT (Espace_responsable_de__production, label79, "label79");

  return Espace_responsable_de__production;
}

GtkWidget*
create_Calendrier_de_plantations (void)
{
  GtkWidget *Calendrier_de_plantations;
  GtkWidget *fixed2;
  GtkWidget *treeview1_cal;
  GtkObject *spinbutton6_rech_adj;
  GtkWidget *spinbutton6_rech;
  GtkWidget *image23;
  GtkWidget *retour1_responsable;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label96;
  GtkWidget *ajouter1_plante;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label78;
  GtkWidget *rechercher;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label114;
  GtkWidget *label115;
  GtkWidget *button_modifier;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label87;
  GtkWidget *button7_actualiser;
  GtkWidget *image25;

  Calendrier_de_plantations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Calendrier_de_plantations), _("Calendrier_de_plantations"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Calendrier_de_plantations), fixed2);

  treeview1_cal = gtk_tree_view_new ();
  gtk_widget_show (treeview1_cal);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1_cal, 224, 48);
  gtk_widget_set_size_request (treeview1_cal, 380, 217);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1_cal), TRUE);

  spinbutton6_rech_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6_rech = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_rech_adj), 1, 0);
  gtk_widget_show (spinbutton6_rech);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton6_rech, 656, 336);
  gtk_widget_set_size_request (spinbutton6_rech, 56, 27);

  image23 = create_pixmap (Calendrier_de_plantations, "45b841c64131e875829588e0e902d1f7.jpg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed2), image23, 32, 8);
  gtk_widget_set_size_request (image23, 768, 520);

  retour1_responsable = gtk_button_new ();
  gtk_widget_show (retour1_responsable);
  gtk_fixed_put (GTK_FIXED (fixed2), retour1_responsable, 112, 336);
  gtk_widget_set_size_request (retour1_responsable, 104, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (retour1_responsable), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox17), label96, FALSE, FALSE, 0);

  ajouter1_plante = gtk_button_new ();
  gtk_widget_show (ajouter1_plante);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter1_plante, 256, 336);
  gtk_widget_set_size_request (ajouter1_plante, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ajouter1_plante), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox4), label78, FALSE, FALSE, 0);

  rechercher = gtk_button_new ();
  gtk_widget_show (rechercher);
  gtk_fixed_put (GTK_FIXED (fixed2), rechercher, 616, 296);
  gtk_widget_set_size_request (rechercher, 104, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (rechercher), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox22), label114, FALSE, FALSE, 0);

  label115 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed2), label115, 544, 336);
  gtk_widget_set_size_request (label115, 104, 32);

  button_modifier = gtk_button_new ();
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifier, 400, 336);
  gtk_widget_set_size_request (button_modifier, 96, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_modifier), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox12), label87, FALSE, FALSE, 0);

  button7_actualiser = gtk_button_new ();
  gtk_widget_show (button7_actualiser);
  gtk_fixed_put (GTK_FIXED (fixed2), button7_actualiser, 736, 296);
  gtk_widget_set_size_request (button7_actualiser, 32, 32);

  image25 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_container_add (GTK_CONTAINER (button7_actualiser), image25);

  g_signal_connect ((gpointer) treeview1_cal, "row_activated",
                    G_CALLBACK (on_treeview1_cal_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour1_responsable, "clicked",
                    G_CALLBACK (on_retour1_responsable_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter1_plante, "clicked",
                    G_CALLBACK (on_ajouter1_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher, "clicked",
                    G_CALLBACK (on_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_actualiser, "clicked",
                    G_CALLBACK (on_button7_actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Calendrier_de_plantations, Calendrier_de_plantations, "Calendrier_de_plantations");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, treeview1_cal, "treeview1_cal");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, spinbutton6_rech, "spinbutton6_rech");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, image23, "image23");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, retour1_responsable, "retour1_responsable");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, image17, "image17");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, label96, "label96");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, ajouter1_plante, "ajouter1_plante");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, image4, "image4");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, label78, "label78");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, image22, "image22");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, label114, "label114");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, label115, "label115");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, image12, "image12");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, label87, "label87");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, button7_actualiser, "button7_actualiser");
  GLADE_HOOKUP_OBJECT (Calendrier_de_plantations, image25, "image25");

  return Calendrier_de_plantations;
}

GtkWidget*
create_Lannee_la_plus_seche (void)
{
  GtkWidget *Lannee_la_plus_seche;
  GtkWidget *fixed3;
  GtkWidget *Bilan_de_l_ann__e_la_plus_s__che;
  GtkWidget *treeview1_anneeplus;
  GtkWidget *boutton_retour2_responsable;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label75;
  GtkWidget *annee_plus_seche;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image26;
  GtkWidget *label116;

  Lannee_la_plus_seche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Lannee_la_plus_seche), _("L'ann\303\251e la plus s\303\251che"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Lannee_la_plus_seche), fixed3);

  Bilan_de_l_ann__e_la_plus_s__che = gtk_label_new (_("Bilan de l'ann\303\251e la plus s\303\251che"));
  gtk_widget_show (Bilan_de_l_ann__e_la_plus_s__che);
  gtk_fixed_put (GTK_FIXED (fixed3), Bilan_de_l_ann__e_la_plus_s__che, 232, 8);
  gtk_widget_set_size_request (Bilan_de_l_ann__e_la_plus_s__che, 376, 32);

  treeview1_anneeplus = gtk_tree_view_new ();
  gtk_widget_show (treeview1_anneeplus);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1_anneeplus, 32, 96);
  gtk_widget_set_size_request (treeview1_anneeplus, 712, 176);

  boutton_retour2_responsable = gtk_button_new ();
  gtk_widget_show (boutton_retour2_responsable);
  gtk_fixed_put (GTK_FIXED (fixed3), boutton_retour2_responsable, 40, 496);
  gtk_widget_set_size_request (boutton_retour2_responsable, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (boutton_retour2_responsable), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox1), label75, FALSE, FALSE, 0);

  annee_plus_seche = gtk_button_new ();
  gtk_widget_show (annee_plus_seche);
  gtk_fixed_put (GTK_FIXED (fixed3), annee_plus_seche, 48, 344);
  gtk_widget_set_size_request (annee_plus_seche, 176, 48);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (annee_plus_seche), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image26 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox23), image26, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("L'ann\303\251e la plus s\303\250che"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox23), label116, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1_anneeplus, "row_activated",
                    G_CALLBACK (on_treeview1_anneeplus_row_activated),
                    NULL);
  g_signal_connect ((gpointer) boutton_retour2_responsable, "clicked",
                    G_CALLBACK (on_boutton_retour2_responsable_clicked),
                    NULL);
  g_signal_connect ((gpointer) annee_plus_seche, "clicked",
                    G_CALLBACK (on_annee_plus_seche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Lannee_la_plus_seche, Lannee_la_plus_seche, "Lannee_la_plus_seche");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, Bilan_de_l_ann__e_la_plus_s__che, "Bilan_de_l_ann__e_la_plus_s__che");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, treeview1_anneeplus, "treeview1_anneeplus");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, boutton_retour2_responsable, "boutton_retour2_responsable");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, image1, "image1");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, label75, "label75");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, annee_plus_seche, "annee_plus_seche");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, image26, "image26");
  GLADE_HOOKUP_OBJECT (Lannee_la_plus_seche, label116, "label116");

  return Lannee_la_plus_seche;
}

GtkWidget*
create_fenetre_ajouter_plante (void)
{
  GtkWidget *fenetre_ajouter_plante;
  GtkWidget *fixed4;
  GtkWidget *nom;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkWidget *label98;
  GtkWidget *label90;
  GtkWidget *label99;
  GtkObject *spinbutton1_anneeajout_adj;
  GtkWidget *spinbutton1_anneeajout;
  GtkWidget *label91;
  GtkWidget *label100;
  GtkWidget *label88;
  GtkWidget *sortie;
  GtkWidget *boutton_ajouter_plante;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label92;
  GtkWidget *boutton_retour4_calendrier;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label94;
  GtkWidget *afficher1_tableau;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label93;
  GtkWidget *combobox2_type;

  fenetre_ajouter_plante = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajouter_plante), _("Ajouter une nouvelle plante"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (fenetre_ajouter_plante), fixed4);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed4), nom, 184, 24);
  gtk_widget_set_size_request (nom, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed4), jour, 248, 104);
  gtk_widget_set_size_request (jour, 56, 24);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed4), mois, 384, 104);
  gtk_widget_set_size_request (mois, 96, 24);

  label98 = gtk_label_new (_("Date de plantation :"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed4), label98, 16, 96);
  gtk_widget_set_size_request (label98, 160, 40);

  label90 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed4), label90, 88, 80);
  gtk_widget_set_size_request (label90, 248, 72);

  label99 = gtk_label_new (_("Type de la plante :"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed4), label99, 40, 184);
  gtk_widget_set_size_request (label99, 176, 32);

  spinbutton1_anneeajout_adj = gtk_adjustment_new (2020, 2020, 2035, 1, 10, 10);
  spinbutton1_anneeajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_anneeajout_adj), 1, 0);
  gtk_widget_show (spinbutton1_anneeajout);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1_anneeajout, 608, 104);
  gtk_widget_set_size_request (spinbutton1_anneeajout, 96, 24);

  label91 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed4), label91, 328, 104);
  gtk_widget_set_size_request (label91, 49, 25);

  label100 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed4), label100, 552, 104);
  gtk_widget_set_size_request (label100, 49, 25);

  label88 = gtk_label_new (_("Nom de la plante:"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed4), label88, 32, 32);
  gtk_widget_set_size_request (label88, 128, 16);

  sortie = gtk_label_new ("");
  gtk_widget_show (sortie);
  gtk_fixed_put (GTK_FIXED (fixed4), sortie, 128, 224);
  gtk_widget_set_size_request (sortie, 248, 24);

  boutton_ajouter_plante = gtk_button_new ();
  gtk_widget_show (boutton_ajouter_plante);
  gtk_fixed_put (GTK_FIXED (fixed4), boutton_ajouter_plante, 208, 248);
  gtk_widget_set_size_request (boutton_ajouter_plante, 112, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (boutton_ajouter_plante), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox13), label92, FALSE, FALSE, 0);

  boutton_retour4_calendrier = gtk_button_new ();
  gtk_widget_show (boutton_retour4_calendrier);
  gtk_fixed_put (GTK_FIXED (fixed4), boutton_retour4_calendrier, 8, 248);
  gtk_widget_set_size_request (boutton_retour4_calendrier, 104, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (boutton_retour4_calendrier), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox15), label94, FALSE, FALSE, 0);

  afficher1_tableau = gtk_button_new ();
  gtk_widget_show (afficher1_tableau);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher1_tableau, 408, 248);
  gtk_widget_set_size_request (afficher1_tableau, 96, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (afficher1_tableau), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox14), label93, FALSE, FALSE, 0);

  combobox2_type = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2_type);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2_type, 216, 184);
  gtk_widget_set_size_request (combobox2_type, 104, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_type), _("Arbre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_type), _("Graine"));

  g_signal_connect ((gpointer) boutton_ajouter_plante, "clicked",
                    G_CALLBACK (on_boutton_ajouter_plante_clicked),
                    NULL);
  g_signal_connect ((gpointer) boutton_retour4_calendrier, "clicked",
                    G_CALLBACK (on_boutton_retour4_calendrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher1_tableau, "clicked",
                    G_CALLBACK (on_afficher1_tableau_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajouter_plante, fenetre_ajouter_plante, "fenetre_ajouter_plante");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, nom, "nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label98, "label98");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label90, "label90");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label99, "label99");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, spinbutton1_anneeajout, "spinbutton1_anneeajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label91, "label91");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label100, "label100");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label88, "label88");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, sortie, "sortie");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, boutton_ajouter_plante, "boutton_ajouter_plante");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, image13, "image13");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label92, "label92");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, boutton_retour4_calendrier, "boutton_retour4_calendrier");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, image15, "image15");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label94, "label94");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, afficher1_tableau, "afficher1_tableau");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, image14, "image14");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, label93, "label93");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter_plante, combobox2_type, "combobox2_type");

  return fenetre_ajouter_plante;
}

GtkWidget*
create_fenetre_afficher_calendrier (void)
{
  GtkWidget *fenetre_afficher_calendrier;
  GtkWidget *fixed5;
  GtkWidget *treeview2_affi_cal;
  GtkWidget *boutton_retour5;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label95;

  fenetre_afficher_calendrier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher_calendrier), _("Afficher le calendrier"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher_calendrier), fixed5);

  treeview2_affi_cal = gtk_tree_view_new ();
  gtk_widget_show (treeview2_affi_cal);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2_affi_cal, 80, 80);
  gtk_widget_set_size_request (treeview2_affi_cal, 300, 200);

  boutton_retour5 = gtk_button_new ();
  gtk_widget_show (boutton_retour5);
  gtk_fixed_put (GTK_FIXED (fixed5), boutton_retour5, 48, 320);
  gtk_widget_set_size_request (boutton_retour5, 104, 24);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (boutton_retour5), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox16), label95, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview2_affi_cal, "row_activated",
                    G_CALLBACK (on_treeview2_affi_cal_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher_calendrier, fenetre_afficher_calendrier, "fenetre_afficher_calendrier");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, treeview2_affi_cal, "treeview2_affi_cal");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, boutton_retour5, "boutton_retour5");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher_calendrier, label95, "label95");

  return fenetre_afficher_calendrier;
}

GtkWidget*
create_fenetre_choix (void)
{
  GtkWidget *fenetre_choix;
  GtkWidget *fixed6;
  GtkWidget *button_lannee_la_plusseche;
  GtkWidget *button_affichage_calendrier;
  GtkWidget *button_retour3_responsable;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label97;

  fenetre_choix = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (fenetre_choix), fixed6);

  button_lannee_la_plusseche = gtk_button_new_with_mnemonic (_("L'ann\303\251e la plus s\303\251che"));
  gtk_widget_show (button_lannee_la_plusseche);
  gtk_fixed_put (GTK_FIXED (fixed6), button_lannee_la_plusseche, 112, 176);
  gtk_widget_set_size_request (button_lannee_la_plusseche, 176, 40);

  button_affichage_calendrier = gtk_button_new_with_mnemonic (_("Afficher le calendrier"));
  gtk_widget_show (button_affichage_calendrier);
  gtk_fixed_put (GTK_FIXED (fixed6), button_affichage_calendrier, 112, 72);
  gtk_widget_set_size_request (button_affichage_calendrier, 176, 40);

  button_retour3_responsable = gtk_button_new ();
  gtk_widget_show (button_retour3_responsable);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retour3_responsable, 24, 296);
  gtk_widget_set_size_request (button_retour3_responsable, 88, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_retour3_responsable), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox18), label97, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_lannee_la_plusseche, "clicked",
                    G_CALLBACK (on_button_lannee_la_plusseche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affichage_calendrier, "clicked",
                    G_CALLBACK (on_button_affichage_calendrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour3_responsable, "clicked",
                    G_CALLBACK (on_button_retour3_responsable_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_choix, fenetre_choix, "fenetre_choix");
  GLADE_HOOKUP_OBJECT (fenetre_choix, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (fenetre_choix, button_lannee_la_plusseche, "button_lannee_la_plusseche");
  GLADE_HOOKUP_OBJECT (fenetre_choix, button_affichage_calendrier, "button_affichage_calendrier");
  GLADE_HOOKUP_OBJECT (fenetre_choix, button_retour3_responsable, "button_retour3_responsable");
  GLADE_HOOKUP_OBJECT (fenetre_choix, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (fenetre_choix, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (fenetre_choix, image18, "image18");
  GLADE_HOOKUP_OBJECT (fenetre_choix, label97, "label97");

  return fenetre_choix;
}

GtkWidget*
create_fenetre_modifier_plante (void)
{
  GtkWidget *fenetre_modifier_plante;
  GtkWidget *fixed7;
  GtkWidget *nom1;
  GtkObject *jour1_adj;
  GtkWidget *jour1;
  GtkObject *mois1_adj;
  GtkWidget *mois1;
  GtkWidget *label103;
  GtkWidget *label105;
  GtkObject *annee1_adj;
  GtkWidget *annee1;
  GtkWidget *label106;
  GtkWidget *label108;
  GtkObject *spinbutton5_id2_adj;
  GtkWidget *spinbutton5_id2;
  GtkWidget *label104;
  GtkWidget *label112;
  GtkWidget *sortie1;
  GtkWidget *label107;
  GtkWidget *button5;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label101;
  GtkWidget *modification;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label111;
  GtkWidget *button6;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label102;
  GtkWidget *combobox3;
  GtkWidget *entry2_type;

  fenetre_modifier_plante = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_modifier_plante), _("Modifier une plante"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (fenetre_modifier_plante), fixed7);

  nom1 = gtk_entry_new ();
  gtk_widget_show (nom1);
  gtk_fixed_put (GTK_FIXED (fixed7), nom1, 184, 24);
  gtk_widget_set_size_request (nom1, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom1), 8226);

  jour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour1 = gtk_spin_button_new (GTK_ADJUSTMENT (jour1_adj), 1, 0);
  gtk_widget_show (jour1);
  gtk_fixed_put (GTK_FIXED (fixed7), jour1, 248, 104);
  gtk_widget_set_size_request (jour1, 56, 24);

  mois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois1 = gtk_spin_button_new (GTK_ADJUSTMENT (mois1_adj), 1, 0);
  gtk_widget_show (mois1);
  gtk_fixed_put (GTK_FIXED (fixed7), mois1, 384, 104);
  gtk_widget_set_size_request (mois1, 96, 24);

  label103 = gtk_label_new (_("Date de plantation :"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed7), label103, 16, 96);
  gtk_widget_set_size_request (label103, 160, 40);

  label105 = gtk_label_new (_("Type de la plante :"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed7), label105, 40, 184);
  gtk_widget_set_size_request (label105, 176, 32);

  annee1_adj = gtk_adjustment_new (2020, 2020, 2035, 1, 10, 10);
  annee1 = gtk_spin_button_new (GTK_ADJUSTMENT (annee1_adj), 1, 0);
  gtk_widget_show (annee1);
  gtk_fixed_put (GTK_FIXED (fixed7), annee1, 608, 104);
  gtk_widget_set_size_request (annee1, 96, 24);

  label106 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed7), label106, 328, 104);
  gtk_widget_set_size_request (label106, 49, 25);

  label108 = gtk_label_new (_("Nom de la plante:"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed7), label108, 8, 24);
  gtk_widget_set_size_request (label108, 176, 32);

  spinbutton5_id2_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton5_id2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_id2_adj), 1, 0);
  gtk_widget_show (spinbutton5_id2);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton5_id2, 528, 24);
  gtk_widget_set_size_request (spinbutton5_id2, 56, 24);

  label104 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed7), label104, 88, 80);
  gtk_widget_set_size_request (label104, 248, 72);

  label112 = gtk_label_new (_("id :"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed7), label112, 464, 24);
  gtk_widget_set_size_request (label112, 49, 25);

  sortie1 = gtk_label_new ("");
  gtk_widget_show (sortie1);
  gtk_fixed_put (GTK_FIXED (fixed7), sortie1, 128, 224);
  gtk_widget_set_size_request (sortie1, 248, 24);

  label107 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed7), label107, 552, 104);
  gtk_widget_set_size_request (label107, 49, 25);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed7), button5, 8, 248);
  gtk_widget_set_size_request (button5, 104, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button5), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox19), label101, FALSE, FALSE, 0);

  modification = gtk_button_new ();
  gtk_widget_show (modification);
  gtk_fixed_put (GTK_FIXED (fixed7), modification, 208, 248);
  gtk_widget_set_size_request (modification, 112, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (modification), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox21), label111, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed7), button6, 408, 248);
  gtk_widget_set_size_request (button6, 96, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button6), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox20), label102, FALSE, FALSE, 0);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox3, 216, 184);
  gtk_widget_set_size_request (combobox3, 104, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Arbre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Graine"));

  entry2_type = gtk_entry_new ();
  gtk_widget_show (entry2_type);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2_type, 352, 184);
  gtk_widget_set_size_request (entry2_type, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_type), 8226);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_boutton_retour4_calendrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) modification, "clicked",
                    G_CALLBACK (on_boutton_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modifier_plante, fenetre_modifier_plante, "fenetre_modifier_plante");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, nom1, "nom1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, jour1, "jour1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, mois1, "mois1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label103, "label103");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label105, "label105");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, annee1, "annee1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label106, "label106");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label108, "label108");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, spinbutton5_id2, "spinbutton5_id2");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label104, "label104");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label112, "label112");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, sortie1, "sortie1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label107, "label107");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, button5, "button5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, image19, "image19");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label101, "label101");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, modification, "modification");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, image21, "image21");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label111, "label111");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, button6, "button6");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, image20, "image20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, label102, "label102");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (fenetre_modifier_plante, entry2_type, "entry2_type");

  return fenetre_modifier_plante;
}

