/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_liste_capteurs (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_enregistrement (void);
GtkWidget* create_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_fenetre_ajouter_enH (void);
GtkWidget* create_fenetre_afficher_enH (void);
GtkWidget* create_fenetre_afficher_enT (void);
GtkWidget* create_fenetre_ajouter_enT (void);
GtkWidget* create_f_chercher_capteur (void);
