/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Espace_responsable_de__production (void);
GtkWidget* create_Calendrier_de_plantations (void);
GtkWidget* create_Lannee_la_plus_seche (void);
GtkWidget* create_fenetre_ajouter_plante (void);
GtkWidget* create_fenetre_afficher_calendrier (void);
GtkWidget* create_fenetre_choix (void);
GtkWidget* create_fenetre_modifier_plante (void);
