/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_de_troupeaux (void);
GtkWidget* create_Ajouter_un_animal (void);
GtkWidget* create_gestion_des___quipement_agricoles (void);
GtkWidget* create_liste_equipement (void);
GtkWidget* create_affectation_equipement (void);
