/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Gestion_de_troupeaux;
  GtkWidget *Ajouter_un_animal;
  GtkWidget *gestion_des___quipement_agricoles;
  GtkWidget *liste_equipement;
  GtkWidget *affectation_equipement;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Gestion_de_troupeaux = create_Gestion_de_troupeaux ();
  gtk_widget_show (Gestion_de_troupeaux);
  Ajouter_un_animal = create_Ajouter_un_animal ();
  gtk_widget_show (Ajouter_un_animal);
  gestion_des___quipement_agricoles = create_gestion_des___quipement_agricoles ();
  gtk_widget_show (gestion_des___quipement_agricoles);
  liste_equipement = create_liste_equipement ();
  gtk_widget_show (liste_equipement);
  affectation_equipement = create_affectation_equipement ();
  gtk_widget_show (affectation_equipement);

  gtk_main ();
  return 0;
}

